#:schema node_modules/wrangler/config-schema.json
name = "after-care"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "DB"
database_name = "after-care-db"
database_id = "after-care-db"

[triggers]
crons = ["* * * * *"]